### ISSUE TITLE
Set up scrapy infrastructure & basic data

### ISSUE THREAD

**Issue by yuriybash** [PhilosophicalPenguin/Journey#12]
- define specific fields we need, add to scraper
- load JSON data for first group of positions (10-20 people per position)

**Comment by edoecohen** [comment]
For MVP - 4 positions - 10 LI profiles per position

**Comment by edoecohen** [comment]
1. Backend engineer
2. Nurse practitioner
3. Deputy attorney general
4. Product manager

**Comment by edoecohen** [comment]
Scraping working. Continue to work on scraping on scale and channeling it to our backend.
